name: Deploy do Site com GitHub Actions

# O pipeline será disparado a cada 'push' (envio de código) na branch main
on:
  push:
    branches: ["main"]

# Permissões necessárias para o Actions conseguir publicar no GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Passo 1: Copia os arquivos do seu repositório para a máquina virtual do GitHub
      - name: Checkout do código
        uses: actions/checkout@v4

      # Passo 2: Configura o ambiente do GitHub Pages
      - name: Configurar o GitHub Pages
        uses: actions/configure-pages@v4

      # Passo 3: Compacta os arquivos HTML, CSS e JS para o envio
      - name: Upload dos arquivos do site
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.' # Indica que queremos enviar todos os arquivos da raiz do projeto

      # Passo 4: Coloca o site no ar e gera o link público
      - name: Publicar no GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
